
services:
  mongodb:
    image: mongo:7.0
    restart: always
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./deployments/mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb/
    env_file:
      - ./deployments/mongodb/.env
    environment:
      # - PUID=1000
      # - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
    - mongodb_network
  
  mongo-express:
    image: mongo-express:1.0.2-18-alpine3.19
    container_name: mongo-express
    restart: no
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    env_file:
      - ./deployments/mongodb/.env
    ports:
      - 8081:8081
    networks:
      - mongodb_network
    depends_on:
      - mongodb

    #command: --auth --bind_ip_all
  redis-cache:
    image: redis:7.4.3
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]


  applicationdb:
    image: postgres:17.4
    container_name: applicationdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data/
    env_file:
      - ./deployments/postgresql/.env
    networks:
      - postgresql_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ghostfree@email.com
      PGADMIN_DEFAULT_PASSWORD: 1QAZ2wsx3EDC$
    volumes:
      - pgadmin_data:/root/.pgadmin
    networks:
      - postgresql_network
    depends_on:
      - applicationdb
    

networks:
  mongodb_network:
    driver: bridge
    name: mongo_network
  postgresql_network:
    driver: bridge
    name: postgres_network

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log

  pgadmin_data:
    driver: local
    external: false
  postgresql:
    driver: local
    external: false
  redis:
    driver: local
    external: false