services:
  redis-cache:
    image: redis:7.4.3
    container_name: rediscache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - redis_network
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: no
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/data
    networks:
      - redis_network
    depends_on:
      - redis-cache


networks:
  redis_network:
    driver: bridge
    name: redis_network

volumes:
  redis:
    driver: local
    external: false
  redisinsight_data:
    driver: local
    external: false