services:
  redis-cache:
    image: redis:7.4.3
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]


volumes:
  redis:
    driver: local
    external: false