services:
  elasticsearch:
    image: docker.elasticsearch.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-container
    restart: always 
    environment:
      - xpack.security.enabled=true
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms256m -Xmx256m ## setting small memory for jvm (save memeory, weakness ram :(( huhu)
    networks:
      - es-net 
    ports:
      - 9200:9200
    volumes:
    - es_data:/usr/share/elasticsearch/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      intervals: 120s
      timeout: 15s
      retries: 5

kibana:
  container_name: kb-container
  image: docker.elastic.co/kibana/kibana:{STACK_VERSION}
  environment:
    - ELASTICSEARCH_HOSTS=http://es-container:9200
    - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
    - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
  networks:
    - es-net
  depends_on:
    - elasticsearch
  ports:
    - 5601:5601
  env_file:
    - .env

networks:
  es-net:
    driver: bridge

volumes:
  es_data:


