services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-secure
    restart: always 
    environment:
      - node.name=es-node
      - cluster.name=secure-cluster
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es-node/es-node.p12
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es-node/es-node.p12
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms256m -Xmx256m ## setting small memory for jvm (save memeory, weakness ram :(( huhu)
    networks:
      - es-net 
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
    - es_data:/usr/share/elasticsearch/data
    - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./certs:/usr/share/elasticsearch/config/certs:ro
    env_file:
      - .env
    healthcheck:
      test: curl --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -u elastic:changeme https://localhost:9200 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    env_file:
      - .env

networks:
  es-net:
    driver: bridge

volumes:
  es_data:


